Indexing

In [5]:
import numpy as np
var = np.array([1,2,3,4])

print(var[1])
print(var[-3])
print(var[0])

2
2
1


In [6]:
var1 = np.array([[1,2,3],[4,5,6]])

print(var1)
print(var1.ndim)
print(var1.shape)
print(var1.size)
print(var1[0,1])

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
2


In [8]:
var3 = np.array([[[1,2,3],[4,5,6]]])
print(var3)
print(var3.ndim)
print(var3.shape)   
print(var3.size)

print(var3[0,1,2])

[[[1 2 3]
  [4 5 6]]]
3
(1, 2, 3)
6
6


Slicing

In [13]:
x = np.array([1,2,3,4,5])

print(x)
print()

print("print 2 to 4 : ", x[1:4])
print ("print 2 to end : ", x[1:])
print ("print start to 4 : ", x[:4])
print ("stop : ", x[1:5:2])

[1 2 3 4 5]

print 2 to 4 :  [2 3 4]
print 2 to end :  [2 3 4 5]
print start to 4 :  [1 2 3 4]
stop :  [2 4]


In [14]:
y = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(y)
print("print 2 to 4 : ", y[0,1:4])
print ("print 2 to end : ", y[0,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
print 2 to 4 :  [2 3 4]
print 2 to end :  [2 3 4 5]


Iteration

In [16]:
x1 = np.array([1,2,3,4,5])

print(x1)

for i in x1:
    print(i)

[1 2 3 4 5]
1
2
3
4
5


In [17]:
x3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(x3)
for i in x3:
    print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[1 2 3 4 5]
[ 6  7  8  9 10]


Copy vs View in Numpy array

In [4]:
import numpy as np
x = np.array([1,2,3,4,5])
y = x.copy()
z= x.view()

print("x : ", x)
print("y : ", y)
print("z : ", z)

x :  [1 2 3 4 5]
y :  [1 2 3 4 5]
z :  [1 2 3 4 5]


Difference :

1) Copy Owns the data, the view does not own the data.
2) Copy of an Array is a new array, view does not create new array
3) The changes made in the copy data does not reflect in original array, it does reflect in case of view array


Join and Split arrays

In [7]:
x = np.array([1,2,3,4,])
y = np.array([5,6,7,8])

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

z = np.concatenate((x,y))
c = np.concatenate((a,b), axis=1)
print(z)
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 5 6]
 [3 4 7 8]]


In [10]:
x = np.array([1,2,3,4,5])

y = np.array_split(x, 3)

print(y)
print(type(y))
print ("y[0] : ", y[0])

[array([1, 2]), array([3, 4]), array([5])]
<class 'list'>
y[0] :  [1 2]


Numpy Array Functions

In [13]:
x = np.array([1,2,3,4,5,2,2,5,8,5,4,2,6])

y = np.where(x == 2)

z = np.where(x%2 == 0)

print(y)
print(z)

(array([ 1,  5,  6, 11]),)
(array([ 1,  3,  5,  6,  8, 10, 11, 12]),)


In [ ]:
x = np.array([1,2,3,4,5])