Creating arrays

In [2]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


Advantages of Numpy arrays over lists

1] Consumes less memory and is convenient to use. It is faster than python lists.
2] It has a lot of built-in functions that can be used to perform operations on arrays. 

Arrays through input

In [9]:
m = []

for i in range(1,6):
    input_value = int(input("Enter value: "))
    m.append(input_value)

print(np.array(m))    

[12 13 14 15 16]


2D, 3D arrays, ndim, shape

In [12]:
ar2 = np.array([[1,2,3],[4,5,6]])
print(ar2)  
print(ar2.ndim)
print(ar2.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [11]:
ar3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ar3)  
print(ar3.ndim)
print(ar3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [17]:
ar_zero = np.zeros((3,4))
ar_one = np.ones((2,3,4),dtype=np.int16)
print(ar_zero)
print(ar_one)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [20]:
ar_rn = np.arange((4))
print(ar_rn)

[0 1 2 3]


In [22]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
x = np.random.rand(4) 
print(x)

[0.54126627 0.4660259  0.86186909 0.01268028]
